### ISSUE TITLE
Doesn't cast shadows on other objects

### ISSUE THREAD

**Issue by SereneMango** [CaptainProton42/FlexibleToonShaderGD#3] opened 2021-11-01 20:48 UTC
Nothing happens after enabling shadows from a light source.

**Comment by CaptainProton42** [comment] 2021-11-01 21:03
Can you elaborate, maybe upload a project that reproduces the error? Also, which Godot version are you on?

Shadows seem to be working fine for me.

**Comment by SereneMango** [comment] 2021-11-01 22:47
It's version 3.3.2.

Objects on the editor have default materials, and they're replaced with others that contain the shader when I run the game: https://youtu.be/IWvcZHnoDjo

**Comment by CaptainProton42** [comment] 2021-11-01 22:59
Thanks!

I cannot repoduce the issue. I'm using this script

```GDScript
extends MeshInstance

const TOON_MATERIAL = preload("res://addons/flexible_toon_shader/FlexibleToonMaterial.tres")

func _ready():
	set_surface_material(0, TOON_MATERIAL.duplicate())
```

to dynamically assign the material to a `MeshInstance`. This is the result:

![image](https://user-images.githubusercontent.com/31868812/139752773-4f73e0fe-746b-4c84-8205-921f5d8296ff.png)

Can you make sure that `use_attenuation` is `true` in the shader params of your material?

![image](https://user-images.githubusercontent.com/31868812/139752954-a80ba152-a81c-41ff-a0b7-c2392e4e8055.png)

**Comment by SereneMango** [comment] 2021-11-02 00:51
Figured out something: the shader can't cast shadows when a mesh is a child of a Viewport, while the Viewport node is a child of a ViewportContainer.

**Comment by CaptainProton42** [comment] 2021-11-02 01:05
Oh it's very interesting that you say that since I have observed something similar for an unrelated project of mine. I thought it was just a mistake I made back then. I don't think the problem you're having is related to the toon material at all but is probably an issue with Godot itself.

If you can confirm that the issue persists with the built-in Godot materials as well, I'll close this issue and you should probably raise it in the main Godot repo.

**Comment by SereneMango** [comment] 2021-11-02 01:09
I made a typo... I meant Camera in the Viewport, not a Mesh.

**Comment by SereneMango** [comment] 2021-11-02 01:12
Yes, I get the same bug with Godot's default material.

Again I'm not using Godot's latest release so I'm unaware if it was fixed at some point.

**Closed as completed** 2021-11-02 01:20 UTC

**Comment by SereneMango** [comment] 2021-11-02 10:40
> Oh it's very interesting that you say that since I have observed something similar for an unrelated project of mine. I thought it was just a mistake I made back then. I don't think the problem you're having is related to the toon material at all but is probably an issue with Godot itself.
> 
> If you can confirm that the issue persists with the built-in Godot materials as well, I'll close this issue and you should probably raise it in the main Godot repo.

Not a bug from the engine, it's just the [viewport needs to have a higher Size value for Shadow Atlas](https://github.com/godotengine/godot/issues/43508). I just tested this and it works.
